=== oisujeh/files_and_resources/commodity-application-modules/mobile-integration/schema/receipt_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationNumber": {
      "type": "string",
	  "description": "This is auto-generated when you pass the text 'WILL BE GENERATED' "
    },
    "instanceType": {
      "type": "string",
	   "description": "This is the operation type uuid, e.g Receipt and Distribution, the uuid is stored in the mapping file"
    },
    "operationDate": {
      "type": "string"
    },
    "destination": {
      "type": "string",
	  "description": "This is the uuid of the stockroom"
    },
    "items": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "calculatedExpiration": {
              "type": "boolean"
            },
            "item": {
              "type": "string"
            },
            "quantity": {
              "type": "integer"
            },
            "itemBatch": {
              "type": "string"
            },
            "expiration": {
              "type": "string"
            }
          },
          "required": [
            "calculatedExpiration",
            "item",
            "quantity",
            "itemBatch",
            "expiration"
          ]
        }
      ]
    },
    "status": {
      "type": "string",
	   "enum": [ "NEW" ] 
    },
    "commoditySource": {
      "type": "string",
	  "enum": ["PEPFAR", "GF", "other donors","GON"] 
    },
    "commodityType": {
      "type": "string",
	  "enum": [ "lab","pharmacy" ] 
    },
    "dataSystem": {
      "type": "string",
	  "enum": [ "mobile" ] 
    }
  },
  "required": [
    "operationNumber",
    "instanceType",
    "operationDate",
    "destination",
    "items",
    "status",
    "commoditySource",
    "commodityType",
    "dataSystem"
  ]
}

=== oisujeh/files_and_resources/commodity-application-modules/mobile-integration/sample json request/sample-create-receipt-request.json
{
   "operationNumber":"WILL BE GENERATED",
   "instanceType":"fce0b4fc-9402-424a-aacb-f99599e51a9f",
   "operationDate":"14-09-2021 11:35",
   "destination":"2741bae2-c5de-43ef-891f-7ec2fd58f442",
   "items":[
      {
         "calculatedExpiration":true,
         "item":"7559842c-0599-429d-90b5-e5935d0cd720",
         "quantity":40,
         "itemBatch":"7YYT63HHS",
         "expiration":"04-11-2022"
      }
   ],
   "status":"NEW",
   "commoditySource":"PEPFAR",
   "commodityType":"lab",
   "dataSystem":"mobile"
}
